<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <RootNamespace>smodr</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Cascadia.RadioBrowser/Cascadia.RadioBrowser.csproj" />
    <ProjectReference Include="../Cascadia.Radio.Services/Cascadia.Radio.Services.csproj" />
  </ItemGroup>
</Project>
