name: Dev Container Validation

on:
  push:
    branches: [ main, develop ]
    paths:
      - '.devcontainer/**'
      - '.github/workflows/devcontainer.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - '.devcontainer/**'
      - '.github/workflows/devcontainer.yml'
  workflow_dispatch:

jobs:
  test:
    name: Test Dev Container
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Build and test dev container
      uses: devcontainers/ci@v0.3
      with:
        imageName: ghcr.io/${{ github.repository }}/devcontainer
        cacheFrom: ghcr.io/${{ github.repository }}/devcontainer
        push: never
        runCmd: |
          dotnet --version
          dotnet restore smodr.sln || echo "Expected restore to fail on Linux for WinUI3 project"
          dotnet format --version
